### ISSUE TITLE
IntesisBox PA-AC-WMP-1

### ISSUE THREAD

**Issue by KlausStoertebeker** [weggetor/ioBroker.airconwithme#162]
Description:
I tried to connect to an "[IntesisBox PA-AC-WMP-1](https://www.intesis.com/products/ac-interfaces/panasonic-gateways/panasonic-ascii-wifi-ac-pa-ac-wmp-1)" with a static IP-address and user "Admin" (standard password "admin"), but the debugging log of ioBroker tells me that there is an authorization error.

Background:
I tried the "AirConwithme" adapter because it's said that it is based upon Intesis ASCII WLAN adapters so I thought I can use it for my IntesisBox. If this adapter wasn't intended to be used with Intesis devices, fell free to close this issue at once.

To Reproduce:
Fill the setup panel with:
IP-address: static IP-adress of the PA-AC-WMP-1
User: Admin (or admin - both reproduce the authorization error)
Password: admin

Expected behavior:
Error free login with the above mentioned credentials

Screenshots & Logfiles:

airconwithme.0 | 2022-08-24 11:04:37.854 | error | Login fehlgeschlagen !
-- | -- | -- | --
airconwithme.0 | 2022-08-24 11:04:37.853 | error | Error: connect ECONNREFUSED 192.168.4.74:80
airconwithme.0 | 2022-08-24 11:04:37.773 | info | config ipaddress: 192.168.4.74
airconwithme.0 | 2022-08-24 11:04:37.748 | info | starting.  Version 0.0.4 (non-npm: weggetor/ioBroker.airconwithme) in  /opt/iobroker/node_modules/iobroker.airconwithme, node: v18.7.0,  js-controller: 4.0.23
airconwithme.0 | 2022-08-24 11:04:37.659 | debug | States connected to redis: 127.0.0.1:9000
airconwithme.0 | 2022-08-24 11:04:37.647 | debug | States create User PubSub Client
airconwithme.0 | 2022-08-24 11:04:37.646 | debug | States create System PubSub Client
airconwithme.0 | 2022-08-24 11:04:37.640 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
airconwithme.0 | 2022-08-24 11:04:37.621 | debug | Objects connected to redis: 127.0.0.1:9001
airconwithme.0 | 2022-08-24 11:04:37.616 | debug | Objects client initialize lua scripts
airconwithme.0 | 2022-08-24 11:04:37.597 | debug | Objects create User PubSub Client
airconwithme.0 | 2022-08-24 11:04:37.596 | debug | Objects create System PubSub Client
airconwithme.0 | 2022-08-24 11:04:37.593 | debug | Objects client ready ... initialize now
airconwithme.0 | 2022-08-24 11:04:37.556 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001

Versions:
 - Adapter version: 0.4
 - JS-Controller version: 4.0.23
 - Node version: 18.7.0
 - Operating system: Xubuntu 22.04 (Xface GUI)

Additional context:  
n/a

**Comment by weggetor** [comment]
Hi Klaus - I don't know your Intesis box and have no way to check if it works (I only owe one Mitsubishi heavy, so thats all I can use for debugging)

When I open the IP in the browser, I see the following:
![image](https://user-images.githubusercontent.com/5718742/186406632-b057b114-6088-4f13-be0a-0aa24f7ab533.png)

Login works with Admin / admin. Is it the same with you ?

**Comment by KlausStoertebeker** [comment]
Hello Torsten,
unfortunately I don't know how to login via Firefox :-( It always adds "https://" to my IP address and then tells me that the page I'm trying to open is insecure :-( But I can ping the IP address and it is alive...
And when I did a set up of my Intesis box I looks exactly like your screen shot. And also the parameters you mention in your description are the same as those described in the manual. I only miss the parameter "temperature" holduing the ambient temperature of the air conditioner...
Regards

Ansgar ;-)

**Comment by weggetor** [comment]
Seems an http / https problem. In my code I only use http:

`this.baseUrl = 'http://' + this.config.ipaddress + '/api.cgi';`

if the intesis webserver in your installation uses https this may be the problem.

**Comment by KlausStoertebeker** [comment]
Hello Torsten,
as I said before I don't know how to connect to my IntesisBox via http-protocol :-( My Firefox-Browser automatically adds the prefix "https://" although I input "http://". And this drives me crazy because I think the IntesisBox doesn't support the https-protocol...
But in the manual (see my first post) is no hint which IP address or port is to be used to access the IntesisBox via web interface.
But I can access the box with the config tool I downloaded from the manufacturers internet page: [[Download](https://www.intesis.com/docs/librariesprovider11/software/wmp-configuration-software-tool.zip?sfvrsn=e554cd7_15&download=true)](url) (there is also mentioned that there is a IntesisBox version for Mitsubishi air conditioners ;-) )
Regards

Ansgar

**Comment by KlausStoertebeker** [comment]
Hello Torsten,
as I said before I don't know how to connect to my IntesisBox via http-protocol :-( My Firefox-Browser automatically adds the prefix "https://" although I input "http://". And this drives me crazy because I think the IntesisBox doesn't support the https-protocol...
But I can access the box with the config tool I downloaded from the manufacturers internet page: [[download here](https://www.intesis.com/docs/librariesprovider11/software/wmp-configuration-software-tool.zip?sfvrsn=e554cd7_15&download=true)] (there is also mentioned that there is a IntesisBox version for Mitsubishi air conditioners ;-) )
And I can access the IntesisBox via a telnet connection (`telnet <ip-address> 3310`), issuing the commands described in the WMP protocol description (see [[here](https://intesis.com/docs/wmp-protocol-specs)]) - maybe this will work for you...
Regards

Ansgar

**Comment by weggetor** [comment]
Hi Klaus - sorry no idea how to test / debug your issue. Closing this now because it's not really an issue with airconwithme adapter, Its more a request to expand the adapter for the intesis box (?). Feel free to fork the repo and add a pull request!
